const root=document.documentElement,toast=document.getElementById('toast'),auth=document.getElementById('authScreen'),app=document.getElementById('appShell');let signup=false;
const users=()=>JSON.parse(localStorage.getItem('cg-users')||'[]');
function theme(t){root.dataset.theme=t;document.getElementById('themeIcon').textContent=t==='dark'?'☼':'☾';localStorage.setItem('cyberguardian-theme',t)}theme(localStorage.getItem('cyberguardian-theme')||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));
document.getElementById('themeToggle').onclick=()=>theme(root.dataset.theme==='dark'?'light':'dark');
function note(m){toast.textContent=m;toast.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function loginView(){document.getElementById('authTitle').textContent=signup?'Create your account':'Welcome back';document.getElementById('authSubtitle').textContent=signup?'Start building a clearer picture of your online safety.':'Sign in to view your protected security dashboard.';document.getElementById('authSubmit').textContent=signup?'Create account →':'Sign in →';document.getElementById('nameLabel').hidden=!signup;document.getElementById('authSwitch').innerHTML=signup?'Already have an account? <button id="switchAuth" type="button">Sign in</button>':'New to CyberGuardian? <button id="switchAuth" type="button">Create an account</button>';document.getElementById('switchAuth').onclick=()=>{signup=!signup;loginView()}}
function openApp(user){auth.hidden=true;app.hidden=false;let name=user.name||'User';document.getElementById('profileName').textContent=name;document.getElementById('greetingName').textContent=name.split(' ')[0];document.getElementById('avatar').textContent=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
document.getElementById('authForm').onsubmit=e=>{e.preventDefault();let email=document.getElementById('authEmail').value.trim().toLowerCase(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim(),error=document.getElementById('authError'),list=users(),user;if(signup){if(!name)return error.textContent='Enter your name to continue.';if(list.some(x=>x.email===email))return error.textContent='An account with that email already exists.';user={name,email,password};list.push(user);localStorage.setItem('cg-users',JSON.stringify(list))}else user=list.find(x=>x.email===email&&x.password===password);if(!user)return error.textContent='Incorrect email or password. Create an account if you are new.';localStorage.setItem('cg-session',user.email);openApp(user)};
document.getElementById('logoutButton').onclick=()=>{localStorage.removeItem('cg-session');app.hidden=true;auth.hidden=false;document.getElementById('authForm').reset()};
document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('runCheck').onclick=()=>note('Security check started.');document.getElementById('reviewButton').onclick=()=>document.querySelector('.recommendations').scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{b.textContent='Completed ✓';b.disabled=true;note('Action marked complete.')});
function page(title,intro,body,aside='Complete an assessment to add activity to your personal dashboard.'){document.getElementById('pageName').textContent=title;document.getElementById('pageContent').innerHTML=`<section class="tool-page"><p class="eyebrow">SECURITY TOOL</p><h1>${title}</h1><p class="subtitle">${intro}</p><div class="tool-grid"><article class="tool-card">${body}</article><aside class="tool-card"><p class="eyebrow">YOUR PROGRESS</p><p class="section-stat">Ready</p><p class="empty-state">${aside}</p></aside></div></section>`}
function password(){page('Password Security','Check password strength privately in your browser. Your password is never saved or sent anywhere.','<p class="eyebrow">LOCAL PASSWORD CHECK</p><h2>Test a password</h2><input id="passwordInput" type="password" placeholder="Enter password to analyze"><button class="primary-button" id="checkPassword">Analyze securely →</button><div class="result-box" id="result">Enter a password to see strength guidance.</div>');document.getElementById('checkPassword').onclick=()=>{let el=document.getElementById('passwordInput'),v=el.value,s=Math.min(100,(v.length>=12?35:v.length*2)+(/[A-Z]/.test(v)?15:0)+(/[a-z]/.test(v)?15:0)+(/\d/.test(v)?15:0)+(/[^\w\s]/.test(v)?15:0)),level=s>=80?'Strong':s>=55?'Good':s>=35?'Fair':'Weak';document.getElementById('result').innerHTML=`<strong>${level} — ${s}/100</strong><br>${s<80?'Use 12+ characters with mixed case, numbers, and symbols.':'Strong length and character variety detected.'}`;el.value=''}}
function scanner(){page('Suspicious URL Scanner','Use local heuristic checks to spot warning signs. CyberGuardian never opens the address you enter.','<p class="eyebrow">SAFE HEURISTIC SCAN</p><h2>Analyze a link</h2><input id="urlInput" type="text" placeholder="https://example.com"><button class="primary-button" id="scan">Scan URL →</button><div class="result-box" id="result">Enter a full URL to run a safety check.</div>');document.getElementById('scan').onclick=()=>{let raw=document.getElementById('urlInput').value.trim();try{let u=new URL(raw),r=0,a=[];if(u.protocol!=='https:'){r+=25;a.push('uses HTTP')}if(/^\d{1,3}(\.\d{1,3}){3}$/.test(u.hostname)){r+=30;a.push('uses an IP address')}if(/@|xn--|login|verify|secure-update/i.test(raw)){r+=25;a.push('contains phishing patterns')}if(u.hostname.split('.').length>4){r+=15;a.push('has excessive subdomains')}let s=r>=50?'DANGEROUS':r>=20?'SUSPICIOUS':'NO OBVIOUS INDICATORS';document.getElementById('result').innerHTML=`<strong>${s} — risk ${r}/100</strong><br>${a.length?'Warning signs: '+a.join(', ')+'.':'No obvious indicators detected. This does not guarantee safety.'}`}catch{document.getElementById('result').innerHTML='<strong>Unable to analyze</strong><br>Please enter a full URL such as https://example.com.'}}}
function checklist(title,items){page(title,'Work through guided checks. Progress is saved separately for each signed-in account.',`<p class="eyebrow">GUIDED CHECKLIST</p><h2>Improve your protection</h2><ul class="check-list">${items.map((x,i)=>`<li><input type="checkbox" id="check${i}"><label for="check${i}">${x}<small>Mark complete after verifying this setting yourself.</small></label></li>`).join('')}</ul>`)}
function phishing(){page('Phishing Simulator','Practice recognizing a simulated message. This scenario is fictional and does not send email.','<p class="eyebrow">SIMULATION 1 OF 3</p><h2>“Urgent: Your package is waiting”</h2><div class="result-box"><strong>From:</strong> Delivery Support &lt;tracking-update@parcel-check.info&gt;<br><br>Your shipment is on hold. Confirm delivery details in 30 minutes to avoid a return fee.<br><br><strong>Link:</strong> parcel-check.info/confirm</div><p>Is this phishing or legitimate?</p><button class="quiz-option" data-answer="no">Legitimate message</button><button class="quiz-option" data-answer="yes">Phishing message</button><div class="result-box" id="result">Choose an answer to see the explanation.</div>');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>document.getElementById('result').innerHTML=`<strong>${b.dataset.answer==='yes'?'Correct.':'Not quite.'}</strong><br>Urgency and a lookalike domain are warning signs. Use the carrier’s official website instead.`)}
function basic(title){page(title,'This protected area is ready for your personal security activity.',`<p class="eyebrow">PERSONAL WORKSPACE</p><h2>${title}</h2><p class="empty-state">There is no activity here yet. Complete an assessment or checklist to build your security history.</p><button class="primary-button" onclick="location.reload()">Return to dashboard →</button>`)}
document.querySelectorAll('.nav-link').forEach(l=>l.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));l.classList.add('active');document.getElementById('sidebar').classList.remove('open');let p=l.dataset.page;if(p==='Dashboard')return location.reload();if(p==='Password Security')return password();if(p==='URL Scanner')return scanner();if(p==='Phishing Simulator')return phishing();if(p==='Account Security')return checklist(p,['Enable multi-factor authentication','Use a unique password','Set recovery email','Review sign-in activity','Store backup codes securely']);if(p==='Device Security')return checklist(p,['Install operating system updates','Enable automatic updates','Turn on screen lock','Enable device encryption','Back up important data']);if(p==='Privacy Checkup')return checklist(p,['Review location access','Review camera access','Review microphone access','Review third-party app access']);basic(p)});
let saved=users().find(x=>x.email===localStorage.getItem('cg-session'));if(saved)openApp(saved);else loginView();
